# Generated by Django 4.2.1 on 2023-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coffees',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coffees',
            field=models.ManyToManyField(null=True, to='CoffeeShop.product'),
        ),
    ]
