# Generated by Django 4.2.1 on 2023-06-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0003_alter_orderitem_coffees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coffees',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coffees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoffeeShop.product'),
        ),
    ]
