# Generated by Django 4.2.1 on 2023-06-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0006_remove_checkout_order_item_checkout_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='coffees',
            new_name='coffee',
        ),
    ]
